import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import sharp from 'sharp';
import { z } from 'zod';

/**
 * Downloads the food photos listed in prisma/data/food-photos/sources.json (slug -> source URL), shrinks each to a
 * 640 px square WebP and writes it next to the manifest as <slug>.webp, where the API serves it from /food-photos.
 *   npm run foods:photos            (only photos that are missing)
 *   npm run foods:photos -- --force (download everything again)
 * Entries with a `credit` come from Wikimedia Commons under an open license (CC BY, CC BY-SA, CC0 or public domain):
 * credit.author and credit.license are what the app owes the photographer. `match: "similar"` means the photo shows
 * the same or a very close dish from a neighbouring cuisine, not that exact Khmer dish: replace those first with
 * our own photos. Entries without a credit are third-party pictures from the original seed CSV.
 * A food whose download fails simply shows an icon in the app. Replace a photo by dropping your own <slug>.webp into
 * the folder (and delete its manifest line so --force doesn't overwrite it).
 */
const DIR = resolve(__dirname, '../prisma/data/food-photos');
const MAX_BYTES = 12 * 1024 * 1024;

const request = (url: string) =>
  fetch(url, {
    headers: { 'user-agent': 'calcam-food-photos/1.0 (https://github.com/calcam; food photo import) Node', accept: 'image/*' },
    signal: AbortSignal.timeout(30_000),
    redirect: 'follow',
  });

const manifest = z
  .record(
    z.string(),
    z.object({
      url: z.url(),
      csvRow: z.string().optional(),
      /** Where the square crop is centred when the automatic choice cuts off the food. */
      position: z.enum(['north', 'south', 'east', 'west', 'centre']).optional(),
      credit: z
        .object({
          title: z.string(),
          author: z.string(),
          license: z.string(),
          page: z.url(),
          match: z.enum(['exact', 'similar']),
        })
        .optional(),
    }),
  )
  .parse(JSON.parse(readFileSync(resolve(DIR, 'sources.json'), 'utf8')));

async function download(url: string): Promise<Buffer> {
  let res = await request(url);
  // Wikimedia asks clients to back off on 429.
  for (let wait = 2000; res.status === 429 && wait <= 16_000; wait *= 2) {
    await new Promise((r) => setTimeout(r, wait));
    res = await request(url);
  }
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const bytes = Buffer.from(await res.arrayBuffer());
  if (bytes.length > MAX_BYTES) throw new Error('file too large');
  return bytes;
}

/** CREDITS.md: who took each Commons photo and under which license (CC BY and CC BY-SA require naming them). */
function writeCredits() {
  const rows = Object.entries(manifest)
    .flatMap(([slug, { credit }]) => (credit ? [{ slug, ...credit }] : []))
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .map(
      (c) =>
        `| ${c.slug} | [${c.title.replace(/^File:/, '').replace(/\|/g, '/')}](${c.page}) | ${c.author.replace(/\|/g, '/') || 'unknown'} | ${c.license} | ${c.match} |`,
    );
  writeFileSync(
    resolve(DIR, 'CREDITS.md'),
    [
      '# Food photo credits',
      '',
      'Generated by `npm run foods:photos` from `sources.json`. Photos are from Wikimedia Commons, resized and cropped to a',
      'square. `similar` means the same or a very close dish from a neighbouring cuisine, not that exact Khmer dish.',
      'Photos without a row here are third-party pictures from the original seed CSV and are not licensed for reuse.',
      '',
      '| Food | Photo | Author | License | Match |',
      '|---|---|---|---|---|',
      ...rows,
      '',
    ].join('\n'),
  );
}

async function main() {
  const force = process.argv.includes('--force');
  mkdirSync(DIR, { recursive: true });
  const failed: string[] = [];
  let written = 0;
  for (const [slug, { url, position }] of Object.entries(manifest)) {
    const file = resolve(DIR, `${slug}.webp`);
    if (!force && existsSync(file)) continue;
    try {
      const webp = await sharp(await download(url))
        .rotate()
        .resize(640, 640, { fit: 'cover', position: position ?? 'attention' })
        .webp({ quality: 76 })
        .toBuffer();
      writeFileSync(file, webp);
      written += 1;
      console.log(`ok     ${slug} (${Math.round(webp.length / 1024)} KB)`);
    } catch (err) {
      failed.push(slug);
      console.log(`failed ${slug}: ${err instanceof Error ? err.message : err}`);
    }
  }
  writeCredits();
  console.log(`\n${written} written, ${failed.length} failed${failed.length ? `: ${failed.join(', ')}` : ''}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
